services:
  db:
    image: mariadb:latest
    networks:
      - heroes-network
    ports:
      - "3306:3306"
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: heroesdatabase
volumes:
  dbdata:
networks:
  heroes-network:
    driver: bridge