services:
  db:
    image: mariadb:latest
    networks:
      - heroes-network
    ports:
      - "3306:3306"
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: heroesdatabase
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heroes-backend
    depends_on:
      - db
    ports:
      - "5162:8080"
    restart: unless-stopped
    networks:
      - heroes-network
volumes:
  dbdata:
networks:
  heroes-network:
    driver: bridge